### ISSUE TITLE
pyinstaller - cannot find files at runtime

### ISSUE THREAD

**Issue by firefu-mc** [gentlegiantJGC/PyMCTranslate#13]
Hi,
I'm running Win 10, python 10.0, under venv in cmd.exe.
Installed module versions are:
```
Package                   Version
------------------------- --------
altgraph                  0.17.2
amulet-core               1.4.8
amulet-nbt                1.0.3.10
future                    0.18.2
numpy                     1.21.4
pefile                    2021.9.3
pip                       21.3.1
pyinstaller               4.7
pyinstaller-hooks-contrib 2021.3
PyMCTranslate             1.0.10
pywin32-ctypes            0.2.0
setuptools                57.4.0
```
pyinstaller builds a single file OK.
Running the .exe triggers the following errors:
```
2021-11-18 22:17:15,913 - amulet_core - INFO - Loading level checkout\McMuncher\local\test2
2021-11-18 22:17:15,971 - amulet_core - INFO - Loading level checkout\McMuncher\local\test1
Dimension: minecraft:the_nether
2021-11-18 22:17:15,986 - amulet_core - ERROR - Error loading chunk -42 33 minecraft:the_nether
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 433, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 484, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 507, in _unpack
  File "amulet\api\wrapper\format_wrapper.py", line 111, in translation_manager
  File "PyMCTranslate\py3\__init__.py", line 22, in new_translation_manager
  File "PyMCTranslate\py3\api\translation_manager\translation_manager.py", line 64, in __init__
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI30482\\PyMCTranslate\\json\\versions'
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 433, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 484, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 507, in _unpack
  File "amulet\api\wrapper\format_wrapper.py", line 111, in translation_manager
  File "PyMCTranslate\py3\__init__.py", line 22, in new_translation_manager
  File "PyMCTranslate\py3\api\translation_manager\translation_manager.py", line 64, in __init__
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI30482\\PyMCTranslate\\json\\versions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mcmuncher.py", line 38, in <module>
  File "mcmuncher.py", line 33, in main
  File "app\submodule\copy_dimensions.py", line 59, in run
  File "app\chunk_utils.py", line 23, in replace_dimension
  File "amulet\api\level\base_level\base_level.py", line 567, in get_chunk
  File "amulet\api\level\base_level\chunk_manager.py", line 187, in get_chunk
  File "amulet\api\history\history_manager\database.py", line 158, in _get_entry
  File "amulet\api\history\history_manager\database.py", line 166, in _get_register_original_entry
  File "amulet\api\level\base_level\chunk_manager.py", line 191, in _raw_get_entry
  File "amulet\api\wrapper\format_wrapper.py", line 452, in load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 438, in _safe_load
amulet.api.errors.ChunkLoadError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI30482\\PyMCTranslate\\json\\versions'
[6756] Failed to execute script 'mcmuncher' due to unhandled exception!
```
I notice the missing path is `[snip]\\PyMCTranslate\\json\\versions`.
However, if I look in my `venv\Lib\site-packages\PyMCTranslate` directory, it contains a `min_json` sub-directory - not a `json` subdir.
So something is making pyinstaller expect the wrong directory name.
Have you seen anything like this before?

**Comment by gentlegiantJGC** [comment]
Not sure. It might be an issue with how we detect paths. You are using one file mode which might break that.
Also it is with noting that our licences don't currently allow redistribution of our code

**Comment by firefu-mc** [comment]
I figured out it's because pyinstaller doesn't bundle non-python files by default.
I managed to get it working by getting the file list with pyinstaller's collect_data_files() and then passing the list to the Analysis() function's 'datas' argument.
I'll PM you separately about the redistribution issue, as it's off topic for this bug report - hope that's ok.
