### ISSUE TITLE
Assertion in `Version` constructor fails

### ISSUE THREAD

**Issue by 0x9fff00** [gentlegiantJGC/PyMCTranslate#44]
Commit 040384c5a43e7dd97088b5cdca2435af6eb4efaa changed the format of the `version` field in the JSON files without updating any of the code that uses it, including this assertion which still expects the old format:

https://github.com/gentlegiantJGC/PyMCTranslate/blob/040384c5a43e7dd97088b5cdca2435af6eb4efaa/PyMCTranslate/py3/api/version/version.py#L79-L81

Because of this, the `TranslationManager` constructor also fails:

```
ERROR - Failed loading translator for version bedrock_1_10_0. Try deleting your Amulet directory and extrating the files agian.
Traceback (most recent call last):
  File "/build/python-pymctranslate-git/src/PyMCTranslate/PyMCTranslate/py3/api/translation_manager/translation_manager.py", line 73, in __init__
    version = Version(os.path.join(versions_path, version_name), self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/python-pymctranslate-git/src/PyMCTranslate/PyMCTranslate/py3/api/version/version.py", line 80, in __init__
    isinstance(init_file["version"], list) and len(init_file["version"]) == 3
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: The version number defined in /build/python-pymctranslate-git/src/PyMCTranslate/PyMCTranslate/json/versions/bedrock_1_10_0/__init__.json is incorrectly formatted
```

**Comment by gentlegiantJGC** [comment]
Thanks for pointing this out
